[package]
name = "audio_converter"
description = "An audio conversion API written in Rust! Supports mp3, ogg, opus, flac, wav & more!"
authors = ["M336"]
version = "2.0.0"
edition = "2021"
repository = "https://github.com/M336G/audio_converter"
license = "MPL-2.0"

[dependencies]
actix-cors = "0.7.2"
actix-files = "0.7.0"
actix-multipart = "0.8.1"
actix-rt = "2.13.0"
actix-web = "4.15.0"
dotenv = "0.15.0"
essi-ffmpeg = "0.3.0"
futures-util = "0.3.34"
infer = "0.22.0"
randomizer = "0.1.2"
serde = { version = "1.0.229", features = ["derive"] }
tokio = "1.53.1"
tokio-util = "0.7.19"