[package]
name = "audio-converter"
description = "An audio conversion API written in Rust! Supports .mp3, .ogg, .opus, .wav & .webm!"
authors = ["M336"]
version = "1.0.1"
edition = "2021"
repository = "https://github.com/M336G/audio-converter"
license = "MPL-2.0"

[dependencies]
actix-cors = "0.7.1"
actix-files = "0.6.6"
actix-rt = "2.10.0"
actix-web = "4.11.0"
dotenv = "0.15.0"
essi-ffmpeg = "0.3.0"
infer = "0.19.0"
randomizer = "0.1.2"
serde = { version = "1.0.219", features = ["derive"] }